name: website-signup
services:
- name: web
  source_dir: /
  github:
    repo: your-username/website-signup
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  build_command: npm run build